# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import todo_pb2 as todo__pb2


class TodosStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addTodo = channel.unary_unary(
        '/todo.Todos/addTodo',
        request_serializer=todo__pb2.AddTodoRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoResponse.FromString,
        )
    self.getTodo = channel.unary_unary(
        '/todo.Todos/getTodo',
        request_serializer=todo__pb2.GetTodoRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoResponse.FromString,
        )
    self.completeTodo = channel.unary_unary(
        '/todo.Todos/completeTodo',
        request_serializer=todo__pb2.CompleteTodoRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoResponse.FromString,
        )
    self.getTodosByStatus = channel.unary_unary(
        '/todo.Todos/getTodosByStatus',
        request_serializer=todo__pb2.GetByStatusRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoCollectionResponse.FromString,
        )
    self.updateStatus = channel.unary_unary(
        '/todo.Todos/updateStatus',
        request_serializer=todo__pb2.UpdateStatusRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoResponse.FromString,
        )
    self.editTodo = channel.unary_unary(
        '/todo.Todos/editTodo',
        request_serializer=todo__pb2.EditTodoRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoResponse.FromString,
        )


class TodosServicer(object):

  def addTodo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTodo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def completeTodo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTodosByStatus(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateStatus(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def editTodo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addTodo': grpc.unary_unary_rpc_method_handler(
          servicer.addTodo,
          request_deserializer=todo__pb2.AddTodoRequest.FromString,
          response_serializer=todo__pb2.TodoResponse.SerializeToString,
      ),
      'getTodo': grpc.unary_unary_rpc_method_handler(
          servicer.getTodo,
          request_deserializer=todo__pb2.GetTodoRequest.FromString,
          response_serializer=todo__pb2.TodoResponse.SerializeToString,
      ),
      'completeTodo': grpc.unary_unary_rpc_method_handler(
          servicer.completeTodo,
          request_deserializer=todo__pb2.CompleteTodoRequest.FromString,
          response_serializer=todo__pb2.TodoResponse.SerializeToString,
      ),
      'getTodosByStatus': grpc.unary_unary_rpc_method_handler(
          servicer.getTodosByStatus,
          request_deserializer=todo__pb2.GetByStatusRequest.FromString,
          response_serializer=todo__pb2.TodoCollectionResponse.SerializeToString,
      ),
      'updateStatus': grpc.unary_unary_rpc_method_handler(
          servicer.updateStatus,
          request_deserializer=todo__pb2.UpdateStatusRequest.FromString,
          response_serializer=todo__pb2.TodoResponse.SerializeToString,
      ),
      'editTodo': grpc.unary_unary_rpc_method_handler(
          servicer.editTodo,
          request_deserializer=todo__pb2.EditTodoRequest.FromString,
          response_serializer=todo__pb2.TodoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.Todos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
