version: "3"
services:
  todo:
    image: imauld/todo:app-0.1.0
    ports:
      - "8081:8081"
    command: "vetodo/bin/python app/run.py"
    volumes:
      - ~/.aws/credentials:/.aws/credentials
    environment:
      - "AWS_ACCESS_KEY_ID=foo"
      - "AWS_SECRET_ACCESS_KEY=bar"
    links:
      - localstack
  localstack:
    image: atlassianlabs/localstack:0.4.3
    ports:
      - "4567-4581:4567-4581"
    environment:
      - "DATA_DIR=/tmp/localstack-todo/data"
    volumes:
      - "localstack_data:/tmp/localstack-todo"
volumes:
  localstack_data:
