FROM python:3.6
MAINTAINER Ian Auld <ian.auld@offerupnow.com>

RUN mkdir /app
COPY requirements.txt /app/requirements.txt
RUN python3 -m venv vetodo && \ 
	/vetodo/bin/pip install -r /app/requirements.txt

