apiVersion: v1
kind: Pod
metadata:
  name: todo
  labels:
    name: todo
spec:
  containers:
  - name: todo
    image: imauld/todo:app-0.1.0
    command: 
      - "/vetodo/bin/python"
    args:
      - "/app/run.py"
    ports:
    - containerPort: 8081
    env:
      - name: "AWS_ACCESS_KEY_ID" 
        value: "foo"
      - name: "AWS_SECRET_ACCESS_KEY"
        value: "bar"